steps:
  - id: Build Docker Image
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']

  - id: Push Image to Repository
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

  - id: Deploy to GKE
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - run
      - --filename=kubernetes.yaml
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
      - --cluster=YOUR-CLUSTER-NAME-HERE
      - --location=europe-west2-a # region or zone