version: "3.9"
services:
  json-to-bigquery:
    build: .
    ports:
    - 80:80
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
    volumes:
    - /var/secrets/google/key.json:/var/secrets/google/key.json